[package]
name = "blind-rsa-signatures"
version = "0.13.0"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "RSA blind signatures in pure Rust"
readme = "README.md"
keywords = ["crypto", "rsa", "blind", "signatures"]
homepage = "https://github.com/jedisct1/rust-blind-rsa-signatures"
repository = "https://github.com/jedisct1/rust-blind-rsa-signatures"
categories = ["cryptography"]
license = "MIT"

[dependencies]
rand = "0.8.5"
rsa = { version = "0.7.2", features = ["expose-internals"] }
digest = "0.10.6"
hmac-sha256 = { version = "1.1.6", features = ["traits010"] }
hmac-sha512 = { version = "1.1.4", features = ["traits010", "sha384"] }
derive-new = "0.5.9"
derive_more = "0.99.17"
